//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYER()
        {
            this.EMPLOYER_STUDENT_CATEGORY = new HashSet<EMPLOYER_STUDENT_CATEGORY>();
        }
    
        public long Person_Id { get; set; }
        public string Employer_Name { get; set; }
        public string Website { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual SEX SEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYER_STUDENT_CATEGORY> EMPLOYER_STUDENT_CATEGORY { get; set; }
    }
}
