//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYER_DESIRED_TIME
    {
        public long Employer_Desired_Time_Id { get; set; }
        public long Employer_Student_Category_Id { get; set; }
        public int Week_Day_Id { get; set; }
        public int Period_Id { get; set; }
    
        public virtual EMPLOYER_STUDENT_CATEGORY EMPLOYER_STUDENT_CATEGORY { get; set; }
        public virtual PERIOD PERIOD { get; set; }
        public virtual WEEK_DAY WEEK_DAY { get; set; }
    }
}
