//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public long News_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string Image_File_Url { get; set; }
        public string Image_Title { get; set; }
        public Nullable<long> Entered_By_Id { get; set; }
        public string Venue { get; set; }
        public Nullable<byte> Hour { get; set; }
        public Nullable<byte> Minute { get; set; }
    }
}
