//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_LEVEL_GRADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public O_LEVEL_GRADE()
        {
            this.TEACHER_O_LEVEL_RESULT_DETAIL = new HashSet<TEACHER_O_LEVEL_RESULT_DETAIL>();
        }
    
        public int O_Level_Grade_Id { get; set; }
        public string O_Level_Grade_Name { get; set; }
        public string O_Level_Grade_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_O_LEVEL_RESULT_DETAIL> TEACHER_O_LEVEL_RESULT_DETAIL { get; set; }
    }
}
