//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OdigoEntities : DbContext
    {
        public OdigoEntities()
            : base("name=OdigoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<EMPLOYER> EMPLOYER { get; set; }
        public virtual DbSet<EMPLOYER_DESIRED_TIME> EMPLOYER_DESIRED_TIME { get; set; }
        public virtual DbSet<EMPLOYER_STUDENT_CATEGORY> EMPLOYER_STUDENT_CATEGORY { get; set; }
        public virtual DbSet<LGA> LGA { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<MESSAGE_TYPE> MESSAGE_TYPE { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<O_LEVEL_EXAM_SITTING> O_LEVEL_EXAM_SITTING { get; set; }
        public virtual DbSet<O_LEVEL_GRADE> O_LEVEL_GRADE { get; set; }
        public virtual DbSet<O_LEVEL_SUBJECT> O_LEVEL_SUBJECT { get; set; }
        public virtual DbSet<O_LEVEL_TYPE> O_LEVEL_TYPE { get; set; }
        public virtual DbSet<OCCUPATION> OCCUPATION { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PAYMENT_CHANNEL> PAYMENT_CHANNEL { get; set; }
        public virtual DbSet<PAYMENT_INTERSWITCH_TRANSACTION> PAYMENT_INTERSWITCH_TRANSACTION { get; set; }
        public virtual DbSet<PAYMENT_MODE> PAYMENT_MODE { get; set; }
        public virtual DbSet<PAYMENT_TERMINAL> PAYMENT_TERMINAL { get; set; }
        public virtual DbSet<PAYMENT_TRANSACTION_STATUS> PAYMENT_TRANSACTION_STATUS { get; set; }
        public virtual DbSet<PAYMENT_WEB> PAYMENT_WEB { get; set; }
        public virtual DbSet<PERIOD> PERIOD { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PERSON_LOGIN> PERSON_LOGIN { get; set; }
        public virtual DbSet<PERSON_TYPE> PERSON_TYPE { get; set; }
        public virtual DbSet<QUALIFICATION> QUALIFICATION { get; set; }
        public virtual DbSet<QUALIFICATION_CATEGORY> QUALIFICATION_CATEGORY { get; set; }
        public virtual DbSet<QUICK_LINK> QUICK_LINK { get; set; }
        public virtual DbSet<RATING> RATING { get; set; }
        public virtual DbSet<REQUEST> REQUEST { get; set; }
        public virtual DbSet<REQUEST_FOR_EMPLOYMENT_COST_IMPLICATION> REQUEST_FOR_EMPLOYMENT_COST_IMPLICATION { get; set; }
        public virtual DbSet<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY> REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY { get; set; }
        public virtual DbSet<REQUEST_STATUS> REQUEST_STATUS { get; set; }
        public virtual DbSet<RIGHT> RIGHT { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<ROLE_RIGHT> ROLE_RIGHT { get; set; }
        public virtual DbSet<SCHOOL_TYPE> SCHOOL_TYPE { get; set; }
        public virtual DbSet<SECURITY_QUESTION> SECURITY_QUESTION { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<SERVICE_CHARGE> SERVICE_CHARGE { get; set; }
        public virtual DbSet<SEX> SEX { get; set; }
        public virtual DbSet<STATE> STATE { get; set; }
        public virtual DbSet<STUDENT_CATEGORY> STUDENT_CATEGORY { get; set; }
        public virtual DbSet<TEACHER> TEACHER { get; set; }
        public virtual DbSet<TEACHER_AVAILABILITY> TEACHER_AVAILABILITY { get; set; }
        public virtual DbSet<TEACHER_AVAILABILITY_STATUS> TEACHER_AVAILABILITY_STATUS { get; set; }
        public virtual DbSet<TEACHER_AWARD> TEACHER_AWARD { get; set; }
        public virtual DbSet<TEACHER_CURRENT_AVAILABILITY> TEACHER_CURRENT_AVAILABILITY { get; set; }
        public virtual DbSet<TEACHER_EDUCATIONAL_QUALIFICATION> TEACHER_EDUCATIONAL_QUALIFICATION { get; set; }
        public virtual DbSet<TEACHER_EMPLOYMENT_HISTORY> TEACHER_EMPLOYMENT_HISTORY { get; set; }
        public virtual DbSet<TEACHER_O_LEVEL_RESULT> TEACHER_O_LEVEL_RESULT { get; set; }
        public virtual DbSet<TEACHER_O_LEVEL_RESULT_DETAIL> TEACHER_O_LEVEL_RESULT_DETAIL { get; set; }
        public virtual DbSet<TEACHER_REFEREE> TEACHER_REFEREE { get; set; }
        public virtual DbSet<TEACHER_STUDENT_CATEGORY> TEACHER_STUDENT_CATEGORY { get; set; }
        public virtual DbSet<TEACHER_TYPE> TEACHER_TYPE { get; set; }
        public virtual DbSet<TEACHER_VERIFICATION_LOG> TEACHER_VERIFICATION_LOG { get; set; }
        public virtual DbSet<TEACHER_VERIFICATION_STATUS> TEACHER_VERIFICATION_STATUS { get; set; }
        public virtual DbSet<TEACHING_COST> TEACHING_COST { get; set; }
        public virtual DbSet<TEACHING_CURRENT_COST> TEACHING_CURRENT_COST { get; set; }
        public virtual DbSet<WEEK_DAY> WEEK_DAY { get; set; }
    }
}
