//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_TRANSACTION_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYMENT_TRANSACTION_STATUS()
        {
            this.PAYMENT_INTERSWITCH_TRANSACTION = new HashSet<PAYMENT_INTERSWITCH_TRANSACTION>();
        }
    
        public short Transaction_Status_Code { get; set; }
        public string Transaction_Status_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT_INTERSWITCH_TRANSACTION> PAYMENT_INTERSWITCH_TRANSACTION { get; set; }
    }
}
