//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_INTERSWITCH_TRANSACTION
    {
        public string Transaction_Ref_No { get; set; }
        public Nullable<long> Payment_Id { get; set; }
        public short Transaction_Status_Code { get; set; }
        public long Amount_In_Kobo { get; set; }
        public string ATM_Card_No { get; set; }
        public string WebPAY_Ref_No { get; set; }
        public string Pay_Ref_No { get; set; }
        public string Status_Reason { get; set; }
        public string Response_Code { get; set; }
        public string Response_Description { get; set; }
        public Nullable<bool> Is_Amount_Mismatch { get; set; }
        public Nullable<System.DateTime> Date_Paid { get; set; }
    
        public virtual PAYMENT_TRANSACTION_STATUS PAYMENT_TRANSACTION_STATUS { get; set; }
        public virtual PAYMENT_WEB PAYMENT_WEB { get; set; }
    }
}
