//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERIOD()
        {
            this.EMPLOYER_DESIRED_TIME = new HashSet<EMPLOYER_DESIRED_TIME>();
            this.TEACHER_AVAILABILITY = new HashSet<TEACHER_AVAILABILITY>();
        }
    
        public int Period_Id { get; set; }
        public string Period_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYER_DESIRED_TIME> EMPLOYER_DESIRED_TIME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_AVAILABILITY> TEACHER_AVAILABILITY { get; set; }
    }
}
