//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.REQUEST = new HashSet<REQUEST>();
            this.REQUEST1 = new HashSet<REQUEST>();
        }
    
        public long Person_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Contact_Address { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public string State_Id { get; set; }
        public int Lga_Id { get; set; }
        public int Country_Id { get; set; }
        public bool Is_Blacklisted { get; set; }
        public System.DateTime Date_Entered { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual EMPLOYER EMPLOYER { get; set; }
        public virtual LGA LGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual PERSON_LOGIN PERSON_LOGIN { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual STATE STATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUEST1 { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
