//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALIFICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUALIFICATION()
        {
            this.TEACHER_EDUCATIONAL_QUALIFICATION = new HashSet<TEACHER_EDUCATIONAL_QUALIFICATION>();
        }
    
        public int Qualification_Id { get; set; }
        public int Qualification_Category_Id { get; set; }
        public int School_Type_Id { get; set; }
        public string Qualification_Name { get; set; }
        public string Qualification_Description { get; set; }
    
        public virtual QUALIFICATION_CATEGORY QUALIFICATION_CATEGORY { get; set; }
        public virtual SCHOOL_TYPE SCHOOL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_EDUCATIONAL_QUALIFICATION> TEACHER_EDUCATIONAL_QUALIFICATION { get; set; }
    }
}
