//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUICK_LINK
    {
        public int Quick_Link_Id { get; set; }
        public string Quick_Link_Name { get; set; }
        public string Quick_Link_Url { get; set; }
        public string Quick_Link_Description { get; set; }
    }
}
