//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_FOR_EMPLOYMENT_COST_IMPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUEST_FOR_EMPLOYMENT_COST_IMPLICATION()
        {
            this.REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY = new HashSet<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY>();
        }
    
        public long Request_For_Employment_Cost_Implication_Id { get; set; }
        public long Request_Id { get; set; }
        public long Employer_Student_Category_Id { get; set; }
        public decimal MonthlyPay { get; set; }
    
        public virtual EMPLOYER_STUDENT_CATEGORY EMPLOYER_STUDENT_CATEGORY { get; set; }
        public virtual REQUEST REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY> REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY { get; set; }
    }
}
