//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOL_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCHOOL_TYPE()
        {
            this.QUALIFICATION = new HashSet<QUALIFICATION>();
            this.TEACHER_EDUCATIONAL_QUALIFICATION = new HashSet<TEACHER_EDUCATIONAL_QUALIFICATION>();
        }
    
        public int School_Type_Id { get; set; }
        public string School_Type_Name { get; set; }
        public string School_Type_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUALIFICATION> QUALIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_EDUCATIONAL_QUALIFICATION> TEACHER_EDUCATIONAL_QUALIFICATION { get; set; }
    }
}
