//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_CATEGORY()
        {
            this.EMPLOYER_STUDENT_CATEGORY = new HashSet<EMPLOYER_STUDENT_CATEGORY>();
            this.TEACHER_STUDENT_CATEGORY = new HashSet<TEACHER_STUDENT_CATEGORY>();
            this.TEACHING_COST = new HashSet<TEACHING_COST>();
        }
    
        public int Student_Category_Id { get; set; }
        public string Student_Category_Name { get; set; }
        public string Student_Category_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYER_STUDENT_CATEGORY> EMPLOYER_STUDENT_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_STUDENT_CATEGORY> TEACHER_STUDENT_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHING_COST> TEACHING_COST { get; set; }
    }
}
