//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_CURRENT_AVAILABILITY
    {
        public long Teacher_Availability_Id { get; set; }
    
        public virtual TEACHER_AVAILABILITY TEACHER_AVAILABILITY { get; set; }
    }
}
