//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_AWARD
    {
        public long Teacher_Award_Id { get; set; }
        public long Person_Id { get; set; }
        public string Award_Body { get; set; }
        public string Award_Name { get; set; }
        public int Year_Awarded { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
