//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
            this.TEACHER_AVAILABILITY = new HashSet<TEACHER_AVAILABILITY>();
            this.TEACHER_AWARD = new HashSet<TEACHER_AWARD>();
            this.TEACHER_EDUCATIONAL_QUALIFICATION = new HashSet<TEACHER_EDUCATIONAL_QUALIFICATION>();
            this.TEACHER_EMPLOYMENT_HISTORY = new HashSet<TEACHER_EMPLOYMENT_HISTORY>();
            this.TEACHER_O_LEVEL_RESULT = new HashSet<TEACHER_O_LEVEL_RESULT>();
            this.TEACHER_STUDENT_CATEGORY = new HashSet<TEACHER_STUDENT_CATEGORY>();
            this.TEACHER_VERIFICATION_LOG = new HashSet<TEACHER_VERIFICATION_LOG>();
        }
    
        public long Person_Id { get; set; }
        public int Teacher_Type_Id { get; set; }
        public byte Sex_Id { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Image_File_Url { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public int Verification_Status_Id { get; set; }
        public int Availability_Status_Id { get; set; }
        public int Rating_Id { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual RATING RATING { get; set; }
        public virtual SEX SEX { get; set; }
        public virtual TEACHER_REFEREE TEACHER_REFEREE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_AVAILABILITY> TEACHER_AVAILABILITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_AWARD> TEACHER_AWARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_EDUCATIONAL_QUALIFICATION> TEACHER_EDUCATIONAL_QUALIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_EMPLOYMENT_HISTORY> TEACHER_EMPLOYMENT_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_O_LEVEL_RESULT> TEACHER_O_LEVEL_RESULT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_STUDENT_CATEGORY> TEACHER_STUDENT_CATEGORY { get; set; }
        public virtual TEACHER_AVAILABILITY_STATUS TEACHER_AVAILABILITY_STATUS { get; set; }
        public virtual TEACHER_TYPE TEACHER_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_VERIFICATION_LOG> TEACHER_VERIFICATION_LOG { get; set; }
        public virtual TEACHER_VERIFICATION_STATUS TEACHER_VERIFICATION_STATUS { get; set; }
    }
}
