//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHING_COST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHING_COST()
        {
            this.REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY = new HashSet<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY>();
        }
    
        public int Teaching_Cost_Id { get; set; }
        public int Student_Category_Id { get; set; }
        public int Qualification_Category_Id { get; set; }
        public int No_Of_Period { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date_Entered { get; set; }
    
        public virtual QUALIFICATION_CATEGORY QUALIFICATION_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY> REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY { get; set; }
        public virtual STUDENT_CATEGORY STUDENT_CATEGORY { get; set; }
        public virtual TEACHING_CURRENT_COST TEACHING_CURRENT_COST { get; set; }
    }
}
