//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_STUDENT_CATEGORY
    {
        public long Teacher_Student_Category_Id { get; set; }
        public long Person_Id { get; set; }
        public int Student_Category_Id { get; set; }
    
        public virtual STUDENT_CATEGORY STUDENT_CATEGORY { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
