//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_EMPLOYMENT_HISTORY
    {
        public long Teacher_Employment_History_Id { get; set; }
        public long Person_Id { get; set; }
        public string Employer { get; set; }
        public string Last_Position_Held { get; set; }
        public int Start_Year { get; set; }
        public int End_Year { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
