//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_REFEREE
    {
        public long Person_Id { get; set; }
        public string Referee_Name { get; set; }
        public string Referee_Contact_Address { get; set; }
        public string Referee_Email_Address { get; set; }
        public string Referee_Mobile_Phone { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
