//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHING_CURRENT_COST
    {
        public int Teaching_Cost_Id { get; set; }
    
        public virtual TEACHING_COST TEACHING_COST { get; set; }
    }
}
