//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odigo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_AVAILABILITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER_AVAILABILITY()
        {
            this.REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY = new HashSet<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY>();
        }
    
        public long Teacher_Availability_Id { get; set; }
        public long Person_Id { get; set; }
        public int Week_Day_Id { get; set; }
        public int Period_Id { get; set; }
    
        public virtual PERIOD PERIOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY> REQUEST_FOR_EMPLOYMENT_TEACHER_AVAILABILITY { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual WEEK_DAY WEEK_DAY { get; set; }
        public virtual TEACHER_CURRENT_AVAILABILITY TEACHER_CURRENT_AVAILABILITY { get; set; }
    }
}
